# Generated by Django 2.1.5 on 2019-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('radius', models.CharField(max_length=100)),
                ('fillColor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circles', models.ManyToManyField(to='MainCanvas.Circle')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.CharField(max_length=100)),
                ('y1', models.CharField(max_length=100)),
                ('x2', models.CharField(max_length=100)),
                ('y2', models.CharField(max_length=100)),
                ('strokeWidth', models.CharField(max_length=100)),
                ('strokeColor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='lines',
            field=models.ManyToManyField(to='MainCanvas.Line'),
        ),
    ]
